In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
data = pd.read_csv('Capres2014-2.0.csv', encoding='latin1')


In [2]:
data.head()

ID        Tweet_ID  \
0   133343972    patih_patria   
1   921720487  RintisBautista   
2 -2120434840      JokowiPres   
3  -116006035      Franliiiii   
4  -906300614      JokowiPres   

                                           Isi_Tweet  Tanggal_Tweet Kandidat  \
0  @FahrelStv Gak setuju Jokowi jadi Cawapres.. C...  8/1/2013 0:33   Jokowi   
1  capres jokowi,wacapres abraham samad. gubernur...  8/1/2013 4:11   Jokowi   
2  RT @RintisBautista: capres jokowi,wacapres abr...  8/1/2013 4:32   Jokowi   
3  capres ( Prabowo ) and cawapres ( jokowi ) and...  8/1/2013 7:33  Prabowo   
4  RT @Franliiiii: capres ( Prabowo ) and cawapre...  8/1/2013 7:36  Prabowo   

                                            Aplikasi  \
0                                                web   
1  <a href="http://janetter.net/" rel="nofollow">...   
2  <a href="http://roundteam.co" rel="nofollow">R...   
3                                                web   
4  <a href="http://roundteam.co" rel="nofollow">R...   

                    Lokasi User  Sentimen  
0            BLITAR - INDONESIA         1  
1  Didalam hatinya recha  :love         1  
2                           NaN         1  
3                        Manado         1  
4                           NaN         1

In [3]:
data.shape
stopwords = pd.read_csv('stopwords_id.csv')
stopwords = stopwords['#stopwords'].values

In [4]:
data.Isi_Tweet.value_counts()

24/09/2013 21:42 Sosok Gubernur Jokowi dan Mantan Wakil Presiden Jusuf Kalla dinyatakan sebagai 2 tokoh terpopuler dalam perbincangan...          59
2013PAN membuka kemungkinan evaluasi pencapresan Ketua Umumnya, Hatta Radjasa. Jika tidak menjadi capres, Hatta bisa menjadi cawapres...          43
2013PAN membuka kemungkinan evaluasi pencapresan Ketua Umumnya, Hatta Radjasa. Jika tidak menjadi capres, Hatta...                                14
RT @Jimie_7: kalo @aniesbaswedan jadi presiden , @jokowi_do2 gubernurnya Jkt, @ridwankamil walikotanya bdg,sy rasa kita pantas optimis sama...    10
RT @oktariands: Jokowi nyapres 2014 OK, tp klo 2019 Hebat. Klo utk 2014 ini bgsny, Mahfud MD Capres, Dahlan Iskan Cawapres. #Pilpres2014           9
RT @fadjroeL: Bungkus "@Nurcholis10: Capres @jokowi_do2. & Cawapres @mohmahfudmd. Gimana bung @fadjroeL.                                           8
RT @TrioMacan2000: Ada yg waras di PDIP @S05sinawang: Guruh masih berfikir jernih"@rezkykamal7: Guruh Suka

In [5]:
from sklearn.model_selection import train_test_split
X = data.Isi_Tweet
y = data.Sentimen

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [6]:
print(X_train.shape)
print(X_test.shape)

(2013,)
(1343,)


In [7]:
vect = CountVectorizer()
X_train_vec = vect.fit(X_train)
X_train_vec.get_feature_names()
X_train_vec = vect.transform(X_train)
X_train_vec

<2013x6508 sparse matrix of type '<class 'numpy.int64'>'
	with 31243 stored elements in Compressed Sparse Row format>

In [8]:
X_test_vec = vect.transform(X_test)
X_test_vec

<1343x6508 sparse matrix of type '<class 'numpy.int64'>'
	with 18652 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
%time nb.fit(X_train_vec, y_train)

CPU times: user 4.51 ms, sys: 30 µs, total: 4.54 ms
Wall time: 4.66 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
y_pred = nb.predict(X_test_vec)

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.7215189873417721

In [14]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_pred, y_test)

array([[185,  49,  24],
       [ 73, 466,  84],
       [ 54,  90, 318]])

In [15]:
y_pred_prob = nb.predict_proba(X_test_vec)
y_pred_prob[0]

array([1.00000000e+00, 8.68749248e-16, 1.37649906e-15])

In [16]:
new_tweet = ['pilih yang bukan koruptor','pilih yang merakyat','golput aja deh']
new_tweet_vect = vect.transform(new_tweet)

nb.predict(new_tweet_vect)

array([1, 1, 1])