# matrix random 5x5

In [8]:
import numpy as np

np.random.seed(2)

In [9]:
matrix_a = np.random.random((5,5))

# matrix_a

In [10]:
min_matrix_a = np.min(matrix_a)

In [11]:
min_matrix_a

0.025926231827891333

In [12]:
max_matrix_a = np.max(matrix_a)
max_matrix_a

0.8539752926394888

# min and max

In [13]:
print("nilai minimum dalam matrix_a: ", min_matrix_a)
print("nilai max dalam matrix_a: ", max_matrix_a)

nilai minimum dalam matrix_a:  0.025926231827891333
nilai max dalam matrix_a:  0.8539752926394888


# normalisasi

In [14]:
z = (matrix_a - min_matrix_a)/(max_matrix_a - min_matrix_a)

In [15]:
z

array([[0.49522267, 0.        , 0.63249422, 0.49441051, 0.47635048],
       [0.36762144, 0.21583552, 0.71655746, 0.33057032, 0.29092605],
       [0.71880717, 0.60771262, 0.13121652, 0.58891666, 0.19143024],
       [0.91710619, 1.        , 0.56555901, 0.99104666, 0.06487447],
       [0.57885442, 0.04753374, 0.4857153 , 0.08526631, 0.12225573]])

# vektor ukuran 10 and sort desc

In [16]:
import numpy as np

np.random.seed(1)
vektor_a = np.random.randint(100,size=10)
vektor_a

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [24]:
np.sort(vektor_a)[::-1]

array([79, 75, 72, 64, 37, 16, 12,  9,  5,  1])