# matrix random 5x5

In [20]:
import numpy as np

np.random.seed(0)

In [21]:
matrix_a = np.random.random((5,5))

# matrix_a

In [23]:
min_matrix_a = np.min(matrix_a)

In [24]:
min_matrix_a

0.02021839744032572

In [25]:
max_matrix_a = np.max(matrix_a)
max_matrix_a

0.978618342232764

# min and max

In [26]:
print("nilai minimum dalam matrix_a: ", min_matrix_a)
print("nilai max dalam matrix_a: ", max_matrix_a)

nilai minimum dalam matrix_a:  0.02021839744032572
nilai max dalam matrix_a:  0.978618342232764


# normalisasi

In [27]:
z = (matrix_a - min_matrix_a)/(max_matrix_a - min_matrix_a)

In [28]:
z

array([[0.55153917, 0.7251367 , 0.60783077, 0.54743825, 0.42094786],
       [0.65283363, 0.43548501, 0.90938507, 0.98439526, 0.37898909],
       [0.80499445, 0.530756  , 0.57160496, 0.94467685, 0.05302344],
       [0.06981522, 0.        , 0.84766433, 0.79083723, 0.88667967],
       [1.        , 0.81275064, 0.46041422, 0.79331263, 0.10231222]])

# vektor ukuran 10 and sort desc

In [40]:
import numpy as np

np.random.seed(1)
vektor_a = np.random.randint(100,size=10)
vektor_a

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [41]:
np.sort(vektor_a)[::-1]

array([79, 75, 72, 64, 37, 16, 12,  9,  5,  1])