# Komputasi Numpy

In [7]:
import numpy as np
np.random.seed(0)

def hitung_luas_lingkaran(jarijari):
    output = np.empty(len(jarijari))
    for i in range(len(jarijari)):
        output[i] = np.pi*jarijari[i]**2
    return output

In [8]:
jarijari = np.random.normal(5.0, 2.0, 10)
hitung_luas_lingkaran(jarijari)

array([228.48354008, 105.6946353 , 152.07341634, 282.44260454,
       239.71059179,  29.13742558, 149.57889284,  69.31764551,
        72.18826837, 106.4570597 ])

In [9]:
big_array = np.random.normal(5.0,2.0, 1000000)
%timeit hitung_luas_lingkaran(big_array)

375 ms ± 6.76 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Ufunc

In [10]:
%timeit np.pi*big_array**2

2.53 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


masking

In [11]:
nilai = np.random.randint(10, size=20)

In [13]:
absen = np.array(list(range(1,21)))

absen[nilai > 6]

In [14]:
absen[(nilai > 6) | (nilai == 1)]

array([ 1,  2,  6,  7,  9, 19])

In [15]:
absen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
nilai

array([8, 9, 1, 5, 6, 9, 8, 2, 8, 0, 2, 1, 4, 4, 0, 0, 3, 4, 9, 3])

In [17]:
absen[(nilai > 6) | (nilai == 1)]

array([ 1,  2,  3,  6,  7,  9, 12, 19])