In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.3'

In [3]:
numpy.pi

3.141592653589793

In [5]:
import numpy as np

In [6]:
np?

In [7]:
clear

In [8]:
a = [3,4,5]
b = [1,1,1]

a = np.array(a)
b = np.array(b)

a+b

array([4, 5, 6])

In [9]:
berat = [66.4, 49.22, 66.3, 88.56, 65.4]
tinggi = [1.75, 1.68, 1.8, 1.81, 1.69]

berat = np.array(berat)
tinggi = np.array(tinggi)

bmi = berat / tinggi ** 2

In [10]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [13]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(a)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.shape

(3, 3)

In [17]:
a[2]

array([7, 8, 9])

In [18]:
a[:, 1]

array([2, 5, 8])

# Pengenalan numpy

Sesi 8

# Attibute Numpy

In [19]:
import numpy as np


In [32]:
np.random.seed(1)
x1 = np.random.randint(10, size=6) #1d
x2 = np.random.randint(10, size=(3,4)) #2d
x3 = np.random.randint(10, size=(3,4,5)) #3d

In [33]:
#  keluarkan atribut pada x3

print("dimensi x3 : ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

dimensi x3 :  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [34]:
print("dtype :", x3.dtype)

dtype : int64


In [35]:
print("itemsize: ", x3.itemsize, "bytes")
print("nsize: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nsize:  480 bytes


In [36]:
x3[1]

array([[3, 6, 5, 1, 9],
       [3, 4, 8, 1, 4],
       [0, 3, 9, 2, 0],
       [4, 9, 2, 7, 7]])